#!/usr/bin/env bash

# Use this as a tag on a JavaScript. After saving your file,
# execute "LintAll" and it'll run ESLint on your project. Any errors
# or warnings should be navigatable.

$(npm bin)/eslint -f unix webpack.config.js "src/**/*.js"